/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {
        boolean runClient = false;
        boolean runServer = false;
        for (String a : args) {
            if ("client".equalsIgnoreCase(a)) runClient = true;
            if ("server".equalsIgnoreCase(a)) runServer = true;
        }
        if (!runClient && !runServer) {
            System.out.println("Usage: java -jar app.jar [client] [server]");
            return;
        }
        if (runClient && runServer) {
            Thread serverThread = new Thread(() -> {
                try {
                    Server.main(new String[0]);
                } catch (Throwable t) {
                    t.printStackTrace();
                }
            }, "server-thread");
            Thread clientThread = new Thread(() -> {
                try {
                    Client.main(new String[0]);
                } catch (Throwable t) {
                    t.printStackTrace();
                }
            }, "client-thread");
            serverThread.start();
            clientThread.start();
            try {
                serverThread.join();
                clientThread.join();
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        } else if (runServer) {
            Server.main(new String[0]);
        } else {
            Client.main(new String[0]);
        }
    }
}
